### ISSUE TITLE
Blank screen on iphone

### ISSUE THREAD

**Issue by Ravavyr** [epranka/soundcode#1]
I’m on an iPhone 8
Both chrome and safari just show a blank screen.
![3F5448DF-5E24-4A42-A380-31599A4C282E](https://user-images.githubusercontent.com/44875133/73937872-009fb080-48b4-11ea-8e90-1830573bb876.png)

**Comment by epranka** [comment]
Maybe you have the option to show the developer console ?

**Comment by epranka** [comment]
I found the issue, it because the MediaRecorder API is not supported in iOS. I will fix it, by removing the option to download the recorded audio in iOS.
